[package]
name = "CC3088-PRO2"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.5.1"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.11.10"
jsonwebtoken = "9"
log = "0.4.30"
sea-orm = { version = "1.1.20", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
url = "2"
utoipa = { version = "5", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
